# 这个工作流程用于将最新的 Release 中的 Publish.zip 同步到腾讯云对象存储

name: Publish

# 控制工作流程何时运行
on:
  release:
    types: [published]

  # 允许在“操作”选项卡中手动运行此工作流程
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Publish:
    # 控制工作流程的运行环境
    runs-on: ubuntu-latest

    # Steps 表示将作为作业的一部分执行的任务序列
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repo
        uses: actions/checkout@v2
        
      # 下载最新的 Release 中的 Publish.zip
      - name: Download Release
        uses: robinraju/release-downloader@v1.3
        with: 
          repository: "DGP-Studio/Snap.Genshin"
          latest: true
          fileName: Publish.zip
          out-file-path: ./release-download
          
      # 将更改上传到腾讯云对象存储
      - name: Upload COS
        uses: zkqiang/tencent-cos-action@v0.1.0
        with:
          args: upload -rs --delete ./release-download/ / -f
          secret_id: ${{ secrets.SECRET_ID }}
          secret_key: ${{ secrets.SECRET_KEY }}
          bucket: ${{ secrets.BUCKET }}
          region: ap-nanjing
