# This is a basic workflow to help you get started with Actions

name: Publish

# Controls when the workflow will run
on:
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repo
        uses: actions/checkout@v2
        
      - name: Download Release
        uses: robinraju/release-downloader@v1.3
        with: 
          repository: "DGP-Studio/Snap.Genshin.Docs"
          latest: true
          fileName: Publish.zip
          out-file-path: ./release-download
          
      - name: Get Latest Release
        id: latest_version
        uses: abatilo/release-info-action@v1.3.0
        with:
          owner: DGP-Studio
          repo: Snap.Genshin.Docs
          
      - name: Upload COS
        uses: zkqiang/tencent-cos-action@v0.1.0
        with:
          args: upload -rs --delete ./release-download latest -f & upload -rs --delete ./release-download ${{ steps.latest_version.outputs.latest_tag }} -f
          secret_id: ${{ secrets.SECRET_ID }}
          secret_key: ${{ secrets.SECRET_KEY }}
          bucket: ${{ secrets.BUCKET }}
          region: ap-nanjing
